export const FETCH_SITES = "FETCH_SITES";
export const FETCH_SITE = "FETCH_SITE";
export const ADD_SITE = "ADD_SITE";
export const EDIT_SITE = "EDIT_SITE";
export const DELETE_SITE = "DELETE_SITE";
export const ADD_POST = "ADD_POST";
export const ADD_COMMENT = "ADD_COMMENT";
export const FETCH_REPORT = "FETCH_REPORT";
export const FETCH_REPORTS = "FETCH_REPORTS";
export const REPORT_LOADING = "REPORT_LOADING";
export const REPORT_FAIL = "REPORT_FAIL";

export const FETCH_IMAGE = "FETCH_IMAGE";
export const FETCHING = "FETCHING";
export const FETCHING_FAIL = "FETCHING_FAIL";

export const UPLOADING_START = "UPLOADING_START";
export const UPLOADING_SUCCESS = "UPLOADING_SUCCESS";
export const UPLOADING_FAIL = "UPLOADING_FAIL";
export const UPLOADING = "UPLOADING";

//user related actions:
export const LOG_IN = "LOG_IN";
export const LOG_OUT = "LOG_OUT";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";
export const CHECK_USER = "CHECK_USER";
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
export const FETCH_AVATAR = "FETCH_AVATAR";
export const AVATAR_UPLOADING_START = "AVATAR_UPLOADING_START";
export const AVATAR_UPLOADING_SUCCESS = "AVATAR_UPLOADING_SUCCESS";
export const AVATAR_UPLOADING_FAIL = "AVATAR_UPLOADING_FAIL";
export const AVATAR_UPLOADING = "AVATAR_UPLOADING";
export const FETCH_VOLUNTEERS_EMAIL = "FETCH_VOLUNTEERS_EMAIL";
export const FETCH_VOLUNTEERS_ID = "FETCH_VOLUNTEERS_ID";
export const FETCH_USER = "FETCH_USER";
