export const FETCH_SITES = "FETCH_SITES";
export const FETCH_SITE = "FETCH_SITE";
export const ADD_SITE = "ADD_SITE";
export const EDIT_SITE = "EDIT_SITE";

export const UPLOADING_START = "UPLOADING_START";
export const UPLOADING_SUCCESS = "UPLOADING_SUCCESS";
export const UPLOADING_FAIL = "UPLOADING_FAIL";
export const UPLOADING = "UPLOADING";
export const FETCH_IMAGE = "FETCH_IMAGE";
//user related actions:
export const LOG_IN = "LOG_IN";
export const LOG_OUT = "LOG_OUT";
export const FETCH_AVATAR = "FETCH_AVATAR";
export const AVATAR_UPLOADING_START = "AVATAR_UPLOADING_START";
export const AVATAR_UPLOADING_SUCCESS = "AVATAR_UPLOADING_SUCCESS";
export const AVATAR_UPLOADING_FAIL = "AVATAR_UPLOADING_FAIL";
export const AVATAR_UPLOADING = "AVATAR_UPLOADING";
